-
  name: init
  hosts: vm
  remote_user: ubuntu
  tasks:
    - name: Install NodeJS v14
      become: yes
      become_user: root
      shell: |
        curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
        apt-get install -y nodejs

    - name: Install yarn
      become: yes
      become_user: root
      shell: |
        curl -sL https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
        echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
        apt update && apt install yarn -y

    - name: Install utils
      become: yes
      become_user: root
      shell: | 
        apt update && apt install git -y
        
    - name: Add env variables
      become: yes
      become_user: root
      shell: |
        cat << EOF > /etc/profile.d/defib_app.sh
        export MONGO_URL="{{ MONGO_URL }}"
        export MONGO_DB={{ MONGO_DB }}
        export MONGO_DB_USER={{ MONGO_DB_USER }}
        export MONGO_DB_PASSWORD={{ MONGO_DB_PASSWORD }}
        export MONGO_DB_HOST={{ MONGO_DB_HOST }}
        export MONGO_DB_NAME={{ MONGO_DB_NAME }}
        export ADMIN_EMAIL={{ ADMIN_EMAIL }}
        export ADMIN_PASSWORD={{ ADMIN_PASSWORD }}
        export SECRET_JWT_KEY_AUTH={{ SECRET_JWT_KEY_AUTH }}
        export EXPIRE_TIME_JWT_AUTH={{ EXPIRE_TIME_JWT_AUTH }}
        export SECRET_JWT_KEY_SIGN_UP={{ SECRET_JWT_KEY_SIGN_UP }}
        export EXPIRE_TIME_JWT_SIGN_UP={{ EXPIRE_TIME_JWT_SIGN_UP }}
        export SECRET_JWT_KEY_RESET={{ SECRET_JWT_KEY_RESET }}
        export EXPIRE_TIME_JWT_RESET={{ EXPIRE_TIME_JWT_RESET }}
        export BASE_URL={{ BASE_URL }}
        export EMAIL_USER={{ EMAIL_USER }}
        export EMAIL_PASSWORD={{ EMAIL_PASSWORD }}
        export EMAIL_FROM={{ EMAIL_FROM }}
        export GOOGLE_API_KEY={{ GOOGLE_API_KEY }}
        EOF
    