name: Build docker images
on:
  push:  
    branches: 
      - master

jobs:
  test:
    name: Build Server image
    runs-on: ubuntu-latest
    env:
      DOCKER_USER: ${{ secrets.DOCKER_USER }}
      DOCKER_PASS: ${{ secrets.DOCKER_PASS }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to DockerHub
      run: docker login -u $DOCKER_USER -p $DOCKER_PASS

    - name: Build docker images
      run: docker-compose build
    
    - name: Push server image to DockerHub
      run: docker push hnom/aed-map-server:latest #todo

    - name: Notify about build status
      uses: up9cloud/action-notify@master
      env:
        GITHUB_JOB_STATUS: ${{ job.status }}
        TELEGRAM_BOT_TOKEN: ${{secrets.TELEGRAM_BOT_TOKEN}}
        TELEGRAM_CHAT_ID: ${{secrets.TELEGRAM_CHAT_ID}}
        CUSTOM_VAR1: ${{github.repository_owner}}
        CUSTOM_VAR2: "a custom variable"

    # - name: Run tests
    #   run: docker-compose run test