name: Build docker images
on:
  push:  
    branches: 
      - develop

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Sleep
      run: sleep 5

    - uses: up9cloud/action-notify@master
      env:
        GITHUB_JOB_STATUS: ${{ job.status }}
        TELEGRAM_BOT_TOKEN: ${{secrets.TELEGRAM_BOT_TOKEN}}
        TELEGRAM_CHAT_ID: ${{secrets.TELEGRAM_CHAT_ID}}
        CUSTOM_VAR1: ${{github.repository_owner}}
        CUSTOM_VAR2: "a custom variable"


    # - name: Run tests
    #   run: docker-compose run test